-- Auto-generated PostgreSQL bootstrap from legacy SQL migrations.
-- Generated by scripts/convert_mysql_migrations_to_pg.py
-- DEPRECATED alone for greenfield (DECISION-014): init/03_spec_indexes.sql restores stripped indexes.

BEGIN;

-- 001_create_users_table.sql
\i /docker-entrypoint-migrations/001_create_users_table.sql

-- 001b_add_kpi_reviewer_role.sql
\i /docker-entrypoint-migrations/001b_add_kpi_reviewer_role.sql

-- 002_create_roles_table.sql
\i /docker-entrypoint-migrations/002_create_roles_table.sql

-- 003_create_clusters_table.sql
\i /docker-entrypoint-migrations/003_create_clusters_table.sql

-- 004_create_skus_table.sql
\i /docker-entrypoint-migrations/004_create_skus_table.sql

-- 005_create_intents_table.sql
\i /docker-entrypoint-migrations/005_create_intents_table.sql

-- 006_create_sku_intents_table.sql
\i /docker-entrypoint-migrations/006_create_sku_intents_table.sql

-- 007_create_audit_results_table.sql
\i /docker-entrypoint-migrations/007_create_audit_results_table.sql

-- 008_create_content_briefs_table.sql
\i /docker-entrypoint-migrations/008_create_content_briefs_table.sql

-- 008b_fix_content_briefs_status_enum.sql
\i /docker-entrypoint-migrations/008b_fix_content_briefs_status_enum.sql

-- 009_create_validation_logs_table.sql
\i /docker-entrypoint-migrations/009_create_validation_logs_table.sql

-- 010_create_tier_history_table.sql
\i /docker-entrypoint-migrations/010_create_tier_history_table.sql

-- 011_create_audit_log_table.sql
\i /docker-entrypoint-migrations/011_create_audit_log_table.sql

-- 011b_alter_audit_log_action_enum.sql
\i /docker-entrypoint-migrations/011b_alter_audit_log_action_enum.sql

-- 012_create_sku_vectors_table.sql
\i /docker-entrypoint-migrations/012_create_sku_vectors_table.sql

-- 013_create_channel_mappings_table.sql
\i /docker-entrypoint-migrations/013_create_channel_mappings_table.sql

-- 015_create_erp_sync_log_table.sql
\i /docker-entrypoint-migrations/015_create_erp_sync_log_table.sql

-- 016_create_staff_effort_logs_table.sql
\i /docker-entrypoint-migrations/016_create_staff_effort_logs_table.sql

-- 017_create_approval_requests_table.sql
\i /docker-entrypoint-migrations/017_create_approval_requests_table.sql

-- 018_create_executive_kpis_table.sql
\i /docker-entrypoint-migrations/018_create_executive_kpis_table.sql

-- 019_add_lock_version_to_skus_table.sql
\i /docker-entrypoint-migrations/019_add_lock_version_to_skus_table.sql

-- 020_add_ai_validation_pending_to_skus_table.sql
\i /docker-entrypoint-migrations/020_add_ai_validation_pending_to_skus_table.sql

-- 021_add_tier_access_to_intents_table.sql
\i /docker-entrypoint-migrations/021_add_tier_access_to_intents_table.sql

-- 022_add_category_to_clusters_table.sql
\i /docker-entrypoint-migrations/022_add_category_to_clusters_table.sql

-- 023_create_ai_audit_tables.sql
\i /docker-entrypoint-migrations/023_create_ai_audit_tables.sql

-- 024_create_canonical_cie_schema.sql
\i /docker-entrypoint-migrations/024_create_canonical_cie_schema.sql

-- 025_alter_sku_gate_status_add_pending.sql
\i /docker-entrypoint-migrations/025_alter_sku_gate_status_add_pending.sql

-- 026_alter_audit_log_to_canonical.sql
\i /docker-entrypoint-migrations/026_alter_audit_log_to_canonical.sql

-- 027_create_v2_3_2_patch_tables.sql
\i /docker-entrypoint-migrations/027_create_v2_3_2_patch_tables.sql

-- 028_alter_ai_golden_queries_intent_type.sql
\i /docker-entrypoint-migrations/028_alter_ai_golden_queries_intent_type.sql

-- 029_add_canonical_cited_sku_business_id.sql
\i /docker-entrypoint-migrations/029_add_canonical_cited_sku_business_id.sql

-- 030_alter_skus_add_decay_fields.sql
\i /docker-entrypoint-migrations/030_alter_skus_add_decay_fields.sql

-- 031_add_erp_velocity_fields_to_skus.sql
\i /docker-entrypoint-migrations/031_add_erp_velocity_fields_to_skus.sql

-- 032_clear_all_users.sql
\i /docker-entrypoint-migrations/032_clear_all_users.sql

-- 033_create_validation_retry_queue.sql
\i /docker-entrypoint-migrations/033_create_validation_retry_queue.sql

-- 034_add_missing_fk_constraints.sql
\i /docker-entrypoint-migrations/034_add_missing_fk_constraints.sql

-- 035_audit_log_canonical_not_null_and_indexes.sql
\i /docker-entrypoint-migrations/035_audit_log_canonical_not_null_and_indexes.sql

-- 036_ai_golden_queries_canonical_not_null.sql
\i /docker-entrypoint-migrations/036_ai_golden_queries_canonical_not_null.sql

-- 037_add_ai_answer_block_and_expert_authority_to_skus.sql
\i /docker-entrypoint-migrations/037_add_ai_answer_block_and_expert_authority_to_skus.sql

-- 038_create_weekly_scores_table.sql
\i /docker-entrypoint-migrations/038_create_weekly_scores_table.sql

-- 039_create_business_rules_table.sql
\i /docker-entrypoint-migrations/039_create_business_rules_table.sql

-- 040_seed_business_rules.sql
\i /docker-entrypoint-migrations/040_seed_business_rules.sql

-- 041_business_rules_audit_and_triggers.sql
\i /docker-entrypoint-migrations/041_business_rules_audit_and_triggers.sql

-- 042_audit_log_immutability_triggers.sql
\i /docker-entrypoint-migrations/042_audit_log_immutability_triggers.sql

-- 042_fix_business_rules_audit_schema.sql
\i /docker-entrypoint-migrations/042_fix_business_rules_audit_schema.sql

-- 043_harvest_tier_access_intents.sql
\i /docker-entrypoint-migrations/043_harvest_tier_access_intents.sql

-- 044_seed_v232_writer_reviewer_users.sql
\i /docker-entrypoint-migrations/044_seed_v232_writer_reviewer_users.sql

-- 045_create_weekly_scores.sql
\i /docker-entrypoint-migrations/045_create_weekly_scores.sql

-- 045b_alter_weekly_scores_columns.sql
\i /docker-entrypoint-migrations/045b_alter_weekly_scores_columns.sql

-- 046_create_semrush_imports_table.sql
\i /docker-entrypoint-migrations/046_create_semrush_imports_table.sql

-- 047_create_gsc_baselines_table.sql
\i /docker-entrypoint-migrations/047_create_gsc_baselines_table.sql

-- 048_add_cis_columns_to_gsc_baselines.sql
\i /docker-entrypoint-migrations/048_add_cis_columns_to_gsc_baselines.sql

-- 050_alter_validation_logs_add_new_gates.sql
\i /docker-entrypoint-migrations/050_alter_validation_logs_add_new_gates.sql

-- 051_ensure_audit_log_timestamp.sql
\i /docker-entrypoint-migrations/051_ensure_audit_log_timestamp.sql

-- 052_ensure_semrush_imports_table.sql
\i /docker-entrypoint-migrations/052_ensure_semrush_imports_table.sql

-- 053_add_user_id_to_validation_logs.sql
\i /docker-entrypoint-migrations/053_add_user_id_to_validation_logs.sql

-- 054_align_validation_logs_with_service.sql
\i /docker-entrypoint-migrations/054_align_validation_logs_with_service.sql

-- 055_enforce_intent_taxonomy.sql
\i /docker-entrypoint-migrations/055_enforce_intent_taxonomy.sql

-- 056_enforce_utc_timezone.sql
\i /docker-entrypoint-migrations/056_enforce_utc_timezone.sql

-- 057_create_url_performance_table.sql
\i /docker-entrypoint-migrations/057_create_url_performance_table.sql

-- 058_create_ga4_landing_performance_table.sql
\i /docker-entrypoint-migrations/058_create_ga4_landing_performance_table.sql

-- 059_gsc_weekly_performance_and_unmatched_urls.sql
\i /docker-entrypoint-migrations/059_gsc_weekly_performance_and_unmatched_urls.sql

-- 060_add_cis_status_to_gsc_baselines.sql
\i /docker-entrypoint-migrations/060_add_cis_status_to_gsc_baselines.sql

-- 060_create_gsc_data_table.sql
\i /docker-entrypoint-migrations/060_create_gsc_data_table.sql

-- 061_add_baseline_content_snapshot.sql
\i /docker-entrypoint-migrations/061_add_baseline_content_snapshot.sql

-- 061_alter_ga4_data_columns.sql
\i /docker-entrypoint-migrations/061_alter_ga4_data_columns.sql

-- 062_create_cis_measurements_table.sql
\i /docker-entrypoint-migrations/062_create_cis_measurements_table.sql

-- 062_remove_amazon_from_channel_enum.sql
\i /docker-entrypoint-migrations/062_remove_amazon_from_channel_enum.sql

-- 063_rename_sku_faqs_to_sku_faq_responses.sql
\i /docker-entrypoint-migrations/063_rename_sku_faqs_to_sku_faq_responses.sql

-- 063_replace_cis_measurements_with_gsc_baselines.sql
\i /docker-entrypoint-migrations/063_replace_cis_measurements_with_gsc_baselines.sql

-- 064_fix_sku_tier_history_columns.sql
\i /docker-entrypoint-migrations/064_fix_sku_tier_history_columns.sql

-- 064_semrush_imports_add_columns_and_rename.sql
\i /docker-entrypoint-migrations/064_semrush_imports_add_columns_and_rename.sql

-- 065_confirm_sku_cluster_mapping.sql
\i /docker-entrypoint-migrations/065_confirm_sku_cluster_mapping.sql

-- 065_create_tier_change_requests_table.sql
\i /docker-entrypoint-migrations/065_create_tier_change_requests_table.sql

-- 066_ai_audit_cron_0600_utc_monday.sql
\i /docker-entrypoint-migrations/066_ai_audit_cron_0600_utc_monday.sql

-- 066_enforce_utc_timezone.sql
\i /docker-entrypoint-migrations/066_enforce_utc_timezone.sql

-- 068_fix_import_batch_id_uuid.sql
\i /docker-entrypoint-migrations/068_fix_import_batch_id_uuid.sql

-- 069_seed_channel_readiness_thresholds.sql
\i /docker-entrypoint-migrations/069_seed_channel_readiness_thresholds.sql

-- 070_add_shopify_pull_columns_to_skus.sql
\i /docker-entrypoint-migrations/070_add_shopify_pull_columns_to_skus.sql

-- 071_add_degraded_mode_to_ai_audit_runs.sql
\i /docker-entrypoint-migrations/071_add_degraded_mode_to_ai_audit_runs.sql

-- 072_add_faq_tables.sql
\i /docker-entrypoint-migrations/072_add_faq_tables.sql

-- 073_add_missing_gate_types_validation_logs.sql
\i /docker-entrypoint-migrations/073_add_missing_gate_types_validation_logs.sql

-- 074_add_bounce_rate_ga4_landing_performance.sql
\i /docker-entrypoint-migrations/074_add_bounce_rate_ga4_landing_performance.sql

-- 075_create_semrush_content_snapshots_table.sql
\i /docker-entrypoint-migrations/075_create_semrush_content_snapshots_table.sql

-- 076_fix_semrush_content_snapshots_fk.sql
\i /docker-entrypoint-migrations/076_fix_semrush_content_snapshots_fk.sql

-- 076_rename_ai_audit_results_columns.sql
\i /docker-entrypoint-migrations/076_rename_ai_audit_results_columns.sql

-- 077_add_erp_sync_date_to_skus.sql
\i /docker-entrypoint-migrations/077_add_erp_sync_date_to_skus.sql

-- 078_alter_sku_gate_status_gate_code_varchar.sql
\i /docker-entrypoint-migrations/078_alter_sku_gate_status_gate_code_varchar.sql

-- 079_drop_sku_gate_status_fk_to_sku_master.sql
\i /docker-entrypoint-migrations/079_drop_sku_gate_status_fk_to_sku_master.sql

-- 080_ensure_skus_ai_answer_block_varchar_300.sql
\i /docker-entrypoint-migrations/080_ensure_skus_ai_answer_block_varchar_300.sql

-- 082_intent_taxonomy_enf_spec_83.sql
\i /docker-entrypoint-migrations/082_intent_taxonomy_enf_spec_83.sql

-- 090_fix_intent_taxonomy_spec_alignment.sql
\i /docker-entrypoint-migrations/090_fix_intent_taxonomy_spec_alignment.sql

-- 091_restore_missing_foreign_keys.sql
\i /docker-entrypoint-migrations/091_restore_missing_foreign_keys.sql

-- 092_add_ai_golden_queries_intent_fk.sql
\i /docker-entrypoint-migrations/092_add_ai_golden_queries_intent_fk.sql

-- 093_fk_enforcement_final_alignment.sql
\i /docker-entrypoint-migrations/093_fk_enforcement_final_alignment.sql

-- 094_add_validation_logs_tier_gate_types.sql
\i /docker-entrypoint-migrations/094_add_validation_logs_tier_gate_types.sql

-- 095_seed_phase5_hardening_rules.sql
\i /docker-entrypoint-migrations/095_seed_phase5_hardening_rules.sql

-- 096_fix_intent_taxonomy_names.sql
\i /docker-entrypoint-migrations/096_fix_intent_taxonomy_names.sql

-- 097_fix_cluster_master_pk.sql
\i /docker-entrypoint-migrations/097_fix_cluster_master_pk.sql

-- 098_fix_sku_master_shape.sql
\i /docker-entrypoint-migrations/098_fix_sku_master_shape.sql

-- 099_fix_sku_content_columns.sql
\i /docker-entrypoint-migrations/099_fix_sku_content_columns.sql

-- 100_create_sku_commercial.sql
\i /docker-entrypoint-migrations/100_create_sku_commercial.sql

-- 101_fix_url_performance.sql
\i /docker-entrypoint-migrations/101_fix_url_performance.sql

-- 102_fix_ga4_landing_performance.sql
\i /docker-entrypoint-migrations/102_fix_ga4_landing_performance.sql

-- 103_create_sku_readiness.sql
\i /docker-entrypoint-migrations/103_create_sku_readiness.sql

-- 104_fix_channel_readiness_enum.sql
\i /docker-entrypoint-migrations/104_fix_channel_readiness_enum.sql

-- 105_fix_sku_tier_history.sql
\i /docker-entrypoint-migrations/105_fix_sku_tier_history.sql

-- 106_fix_content_briefs.sql
\i /docker-entrypoint-migrations/106_fix_content_briefs.sql

-- 107_add_missing_columns_to_sku_master.sql
\i /docker-entrypoint-migrations/107_add_missing_columns_to_sku_master.sql

-- 108_add_missing_columns_to_sku_content.sql
\i /docker-entrypoint-migrations/108_add_missing_columns_to_sku_content.sql

-- 109_intent_taxonomy_add_is_active.sql
\i /docker-entrypoint-migrations/109_intent_taxonomy_add_is_active.sql

-- 110_intent_taxonomy_labels_spec_alignment.sql
\i /docker-entrypoint-migrations/110_intent_taxonomy_labels_spec_alignment.sql

-- 111_url_performance_unique_sku_week.sql
\i /docker-entrypoint-migrations/111_url_performance_unique_sku_week.sql

-- 112_ga4_landing_fk_and_unique_sku_week.sql
\i /docker-entrypoint-migrations/112_ga4_landing_fk_and_unique_sku_week.sql

-- 114_sku_tier_history_add_changed_by.sql
\i /docker-entrypoint-migrations/114_sku_tier_history_add_changed_by.sql

-- 115_ai_audit_results_spec_columns.sql
\i /docker-entrypoint-migrations/115_ai_audit_results_spec_columns.sql

-- 116_semrush_imports_spec_columns.sql
\i /docker-entrypoint-migrations/116_semrush_imports_spec_columns.sql

-- 117_seed_business_rules_channel_harvest_and_cache_ttl.sql
\i /docker-entrypoint-migrations/117_seed_business_rules_channel_harvest_and_cache_ttl.sql

-- 120_fix_content_briefs_status_lowercase.sql
\i /docker-entrypoint-migrations/120_fix_content_briefs_status_lowercase.sql

-- 121_add_landing_page_path_alias.sql
\i /docker-entrypoint-migrations/121_add_landing_page_path_alias.sql

-- 122_seed_writer_reviewer_users.sql
\i /docker-entrypoint-migrations/122_seed_writer_reviewer_users.sql

-- 123_fix_intent_taxonomy_label_width.sql
\i /docker-entrypoint-migrations/123_fix_intent_taxonomy_label_width.sql

-- 124_seed_tier_commercial_formula_scale_rules.sql
\i /docker-entrypoint-migrations/124_seed_tier_commercial_formula_scale_rules.sql

-- 125_create_ai_agent_logs_table.sql
\i /docker-entrypoint-migrations/125_create_ai_agent_logs_table.sql

-- 126_seed_cables_golden_questions.sql
\i /docker-entrypoint-migrations/126_seed_cables_golden_questions.sql

-- 127_add_erp_data_incomplete_to_skus.sql
\i /docker-entrypoint-migrations/127_add_erp_data_incomplete_to_skus.sql

-- 128_semrush_imports_spec_keyword_diff_url.sql
\i /docker-entrypoint-migrations/128_semrush_imports_spec_keyword_diff_url.sql

-- 129_seed_channel_score_deltas_business_rules.sql
\i /docker-entrypoint-migrations/129_seed_channel_score_deltas_business_rules.sql

-- 130_seed_queue_priority_business_rules.sql
\i /docker-entrypoint-migrations/130_seed_queue_priority_business_rules.sql

-- 131_semrush_imports_canonical_ddl_documentation.sql
\i /docker-entrypoint-migrations/131_semrush_imports_canonical_ddl_documentation.sql

-- 132_seed_cc5_channel_and_measurement_rules.sql
\i /docker-entrypoint-migrations/132_seed_cc5_channel_and_measurement_rules.sql

-- 134_add_ga4_baseline_and_measurement_status_to_gsc_baselines.sql
\i /docker-entrypoint-migrations/134_add_ga4_baseline_and_measurement_status_to_gsc_baselines.sql

-- 135_align_cis_ga4_columns_in_gsc_baselines.sql
\i /docker-entrypoint-migrations/135_align_cis_ga4_columns_in_gsc_baselines.sql

-- 136_add_source_to_gsc_unmatched_urls.sql
\i /docker-entrypoint-migrations/136_add_source_to_gsc_unmatched_urls.sql

-- 137_create_sync_status_table.sql
\i /docker-entrypoint-migrations/137_create_sync_status_table.sql

-- 138_alter_ai_agent_logs_add_prompt_response.sql
\i /docker-entrypoint-migrations/138_alter_ai_agent_logs_add_prompt_response.sql

-- 139_add_sku_code_to_sku_master.sql
\i /docker-entrypoint-migrations/139_add_sku_code_to_sku_master.sql

-- 140_add_run_status_to_ai_audit_runs.sql
\i /docker-entrypoint-migrations/140_add_run_status_to_ai_audit_runs.sql

-- 141_add_patch2_degradation_columns_to_ai_audit_runs.sql
\i /docker-entrypoint-migrations/141_add_patch2_degradation_columns_to_ai_audit_runs.sql

-- 142_seed_additional_ai_business_rules.sql
\i /docker-entrypoint-migrations/142_seed_additional_ai_business_rules.sql

-- 143_add_decay_notifications_and_revenue_risk.sql
\i /docker-entrypoint-migrations/143_add_decay_notifications_and_revenue_risk.sql

-- 144_seed_readiness_component_weights.sql
\i /docker-entrypoint-migrations/144_seed_readiness_component_weights.sql

-- 145_create_cluster_vectors_table.sql
\i /docker-entrypoint-migrations/145_create_cluster_vectors_table.sql

-- 146_scrub_user_login_data.sql
\i /docker-entrypoint-migrations/146_scrub_user_login_data.sql

-- 147_prevent_kill_tier_update_trigger.sql
\i /docker-entrypoint-migrations/147_prevent_kill_tier_update_trigger.sql

-- 148_drop_semrush_imports_table.sql
\i /docker-entrypoint-migrations/148_drop_semrush_imports_table.sql

-- 149_fix_tier_enum_lowercase.sql
\i /docker-entrypoint-migrations/149_fix_tier_enum_lowercase.sql

-- 150_add_vector_retry_queue.sql
\i /docker-entrypoint-migrations/150_add_vector_retry_queue.sql

-- 151_gates_tier_max_secondary_rules.sql
\i /docker-entrypoint-migrations/151_gates_tier_max_secondary_rules.sql

-- 152_business_rules_vector_similarity_threshold_alias.sql
\i /docker-entrypoint-migrations/152_business_rules_vector_similarity_threshold_alias.sql

-- 153_seed_cis_small_improvement_rules.sql
\i /docker-entrypoint-migrations/153_seed_cis_small_improvement_rules.sql

-- 154_seed_audit_threshold_rules.sql
\i /docker-entrypoint-migrations/154_seed_audit_threshold_rules.sql

-- 155_backfill_ai_answer_block_from_long_description.sql
\i /docker-entrypoint-migrations/155_backfill_ai_answer_block_from_long_description.sql

-- 156_seed_channel_weight_rules.sql
\i /docker-entrypoint-migrations/156_seed_channel_weight_rules.sql

-- 157_seed_validate_sla_rule.sql
\i /docker-entrypoint-migrations/157_seed_validate_sla_rule.sql

-- 158_fix_business_rules_audit_contract.sql
\i /docker-entrypoint-migrations/158_fix_business_rules_audit_contract.sql

-- 159_expand_content_briefs_status_enum_for_spec_compat.sql
\i /docker-entrypoint-migrations/159_expand_content_briefs_status_enum_for_spec_compat.sql

-- 160_create_cis_measurements_spec_compat.sql
\i /docker-entrypoint-migrations/160_create_cis_measurements_spec_compat.sql

-- 161_create_tier_assignments_spec_compat.sql
\i /docker-entrypoint-migrations/161_create_tier_assignments_spec_compat.sql

-- 162_create_sku_cluster_map_spec_compat.sql
\i /docker-entrypoint-migrations/162_create_sku_cluster_map_spec_compat.sql

-- 163_ensure_weekly_scores_spec_columns.sql
\i /docker-entrypoint-migrations/163_ensure_weekly_scores_spec_columns.sql

-- 164_enforce_utc_session_timezone_safe.sql
\i /docker-entrypoint-migrations/164_enforce_utc_session_timezone_safe.sql

-- 165_audit_log_action_enum_and_indexes_compat.sql
\i /docker-entrypoint-migrations/165_audit_log_action_enum_and_indexes_compat.sql

-- 166_ensure_semrush_imports_table.sql
\i /docker-entrypoint-migrations/166_ensure_semrush_imports_table.sql

COMMIT;
