CREATE TABLE roles (
 id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
 name VARCHAR(50) NOT NULL UNIQUE,
 display_name VARCHAR(100),
 description TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE user_roles (
 user_id CHAR(36) NOT NULL,
 role_id CHAR(36) NOT NULL,
 assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 assigned_by CHAR(36),
 PRIMARY KEY (user_id, role_id),
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
 FOREIGN KEY (assigned_by) REFERENCES users(id) ON DELETE SET NULL
);
