SET NAMES utf8mb4;

CREATE TABLE skus (
 id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
 sku_code VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL UNIQUE,
 title VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
 short_description TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
 long_description TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
 meta_title VARCHAR(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
 meta_description VARCHAR(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
 tier ENUM('hero','support','harvest','kill') NOT NULL DEFAULT 'support',
 tier_rationale TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
 primary_cluster_id CHAR(36),
 validation_status ENUM('DRAFT', 'PENDING', 'VALID', 'INVALID', 'DEGRADED') DEFAULT 'DRAFT',
 last_validated_at TIMESTAMP NULL,
 can_publish BOOLEAN DEFAULT false,
 current_price DECIMAL(10, 2),
 cost DECIMAL(10, 2),
 margin_percent DECIMAL(5, 2),
 annual_volume INT,
 last_sale_date DATE,
 strategic_hero BOOLEAN DEFAULT false,
  erp_cppc DECIMAL(8, 4) DEFAULT 0.0000,
  erp_return_rate_pct DECIMAL(5, 2) DEFAULT 0.00,
  best_for TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  not_for TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  faq_data JSON,
  content_score INT DEFAULT 0,
  schema_score INT DEFAULT 0,
  commercial_score DECIMAL(8, 4) DEFAULT 0.0000,
  readiness_score INT DEFAULT 0,
  score_answer_block INT DEFAULT 0,
  score_faq INT DEFAULT 0,
  score_safety INT DEFAULT 0,
  score_comparison INT DEFAULT 0,
  score_structured_data INT DEFAULT 0,
  score_citation INT DEFAULT 0,
  decay_weeks INT DEFAULT 0,
  last_audit_quorum INT DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 created_by CHAR(36),
 updated_by CHAR(36),
 INDEX idx_sku_code (sku_code),
 INDEX idx_tier (tier),
 INDEX idx_validation_status (validation_status),
 INDEX idx_cluster (primary_cluster_id),
 FOREIGN KEY (primary_cluster_id) REFERENCES clusters(id) ON DELETE SET NULL,
 FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
 FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
