SET NAMES utf8mb4;

CREATE TABLE intents (
 id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
 name VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL UNIQUE,
 display_name VARCHAR(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
 description TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
 is_locked BOOLEAN DEFAULT true,
 sort_order INT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
