CREATE TABLE intents (
 id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
 name VARCHAR(100) NOT NULL UNIQUE,
 display_name VARCHAR(150),
 description TEXT,
 is_locked BOOLEAN DEFAULT true,
 sort_order INT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_name (name)
);
