CREATE TABLE content_briefs (
 id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
 sku_id CHAR(36) NOT NULL,
 brief_type ENUM('DECAY_REFRESH', 'NEW_PRODUCT', 'MANUAL', 'SEASONAL') DEFAULT 'MANUAL',
 priority ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT') DEFAULT 'MEDIUM',
 title VARCHAR(255) NOT NULL,
 description TEXT,
 current_content TEXT,
 suggested_actions JSON,
 status ENUM('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED') DEFAULT 'OPEN',
 assigned_to CHAR(36),
 deadline DATE,
 effort_estimate_hours DECIMAL(5, 2),
 actual_hours DECIMAL(5, 2),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 completed_at TIMESTAMP NULL,
 FOREIGN KEY (sku_id) REFERENCES skus(id) ON DELETE CASCADE,
 FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL,
 INDEX idx_sku (sku_id),
 INDEX idx_status (status),
 INDEX idx_assigned (assigned_to),
 INDEX idx_deadline (deadline)
);
