CREATE TABLE cluster_vectors (
 id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
 cluster_id CHAR(36) NOT NULL,
 vector JSON NOT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (cluster_id) REFERENCES clusters(id) ON DELETE CASCADE
);
