-- CIE v2.3.2 – Seed exactly 52 business rules. No hard-coded values in tier/gate/readiness engines.

INSERT INTO business_rules (id, rule_key, value, value_type, description) VALUES
(UUID(), 'gates.vector_similarity_min', '0.72', 'float', 'Minimum cosine similarity for vector gate (fail below, pass at or above)'),
(UUID(), 'tier.margin_weight', '0.40', 'float', 'Commercial score weight for contribution margin'),
(UUID(), 'tier.cppc_weight', '0.25', 'float', 'Commercial score weight for CPPC'),
(UUID(), 'tier.velocity_weight', '0.20', 'float', 'Commercial score weight for velocity_90d'),
(UUID(), 'tier.returns_weight', '0.15', 'float', 'Commercial score weight for return rate'),
(UUID(), 'tier.manual_override_expiry_days', '90', 'integer', 'Days after which manual tier override expires'),
(UUID(), 'readiness.valid_cluster_id', '10', 'integer', 'CIS points for valid cluster'),
(UUID(), 'readiness.has_primary_intent', '10', 'integer', 'CIS points for primary intent'),
(UUID(), 'readiness.has_secondary_intents', '10', 'integer', 'CIS points for secondary intents'),
(UUID(), 'readiness.answer_block_passes_g4', '15', 'integer', 'CIS points for answer block'),
(UUID(), 'readiness.best_for_not_for_populated', '10', 'integer', 'CIS points for best_for/not_for'),
(UUID(), 'readiness.expert_authority_present', '10', 'integer', 'CIS points for expert authority'),
(UUID(), 'readiness.json_ld_renders_valid', '10', 'integer', 'CIS points for JSON-LD'),
(UUID(), 'readiness.images_meet_channel', '10', 'integer', 'CIS points for images'),
(UUID(), 'readiness.pricing_present', '10', 'integer', 'CIS points for pricing'),
(UUID(), 'readiness.category_specific_complete', '5', 'integer', 'CIS points for category complete'),
(UUID(), 'gates.answer_block_min_chars', '250', 'integer', 'Minimum character count for answer block'),
(UUID(), 'gates.answer_block_max_chars', '300', 'integer', 'Maximum character count for answer block'),
(UUID(), 'readiness.hero_primary_threshold', '85', 'integer', 'Hero: min readiness on primary channel'),
(UUID(), 'readiness.hero_all_channels_threshold', '70', 'integer', 'Hero: min readiness on all active channels'),
(UUID(), 'audit.weekly_day', 'Monday', 'string', 'Day of week for weekly AI audit'),
(UUID(), 'audit.weekly_time_utc', '09:00', 'string', 'Time UTC for weekly AI audit run'),
(UUID(), 'decay.week1_status', 'yellow_flag', 'string', 'Decay status after 1 week zero'),
(UUID(), 'decay.week2_status', 'alert', 'string', 'Decay status after 2 weeks zero'),
(UUID(), 'decay.week3_status', 'auto_brief', 'string', 'Decay status after 3 weeks zero'),
(UUID(), 'decay.week4_status', 'escalated', 'string', 'Decay status after 4+ weeks zero'),
(UUID(), 'cis.d15_measurement_days', '15', 'integer', 'Days for D+15 measurement'),
(UUID(), 'cis.d30_measurement_days', '30', 'integer', 'Days for D+30 CIS score'),
(UUID(), 'channel.google_sge_weight', '1.0', 'float', 'Channel weight Google SGE'),
(UUID(), 'channel.amazon_weight', '1.0', 'float', 'Channel weight Amazon'),
(UUID(), 'channel.ai_assistants_weight', '1.0', 'float', 'Channel weight AI assistants'),
(UUID(), 'channel.own_website_weight', '1.0', 'float', 'Channel weight own website'),
(UUID(), 'intent.taxonomy_locked_count', '9', 'integer', 'Number of locked intents'),
// SOURCE: CIE_Master_Developer_Build_Spec.docx Section 5.3 — tier hero/support/harvest percentile thresholds
(UUID(), 'g3.hero_secondary_max', '3', 'integer', 'Max secondary intents for Hero'),
(UUID(), 'g3.support_secondary_max', '2', 'integer', 'Max secondary intents for Support'),
(UUID(), 'g3.harvest_secondary_max', '1', 'integer', 'Max secondary intents for Harvest'),
(UUID(), 'g5.best_for_min', '2', 'integer', 'Minimum best_for entries for Hero/Support'),
(UUID(), 'g5.not_for_min', '1', 'integer', 'Minimum not_for entries for Hero/Support'),
(UUID(), 'tier.hero_percentile_threshold', '0.80', 'float', 'Cohort percentile threshold for Hero (p80)'),
(UUID(), 'tier.support_percentile_threshold', '0.30', 'float', 'Cohort percentile threshold for Support (p30)'),
(UUID(), 'tier.harvest_percentile_threshold', '0.10', 'float', 'Cohort percentile threshold for Harvest (p10)'),
(UUID(), 'audit.quorum_advance_min', '3', 'integer', 'Min engines for decay advance (3/4)'),
(UUID(), 'audit.quorum_pause', '2', 'integer', 'Engines for decay pause (2/4)'),
(UUID(), 'audit.score_min', '0', 'integer', 'Audit score minimum (integer 0-3)'),
(UUID(), 'audit.score_max', '3', 'integer', 'Audit score maximum (integer 0-3)'),
(UUID(), 'weekly_scores.score_min', '1', 'integer', 'Weekly KPI score minimum'),
(UUID(), 'weekly_scores.score_max', '10', 'integer', 'Weekly KPI score maximum'),
(UUID(), 'content.title_max_length', '250', 'integer', 'Max title length'),
(UUID(), 'content.description_min_length', '50', 'integer', 'Min short description length'),
(UUID(), 'content.description_vector_min_length', '100', 'integer', 'Min long description length for vector validation'),
(UUID(), 'validation.http_fail_status', '400', 'integer', 'HTTP status when validation fails with blocking errors'),
(UUID(), 'audit_log.immutable', 'true', 'boolean', 'Audit log allows no UPDATE/DELETE'),
(UUID(), 'harvest.intent_primary_allowed', 'specification', 'string', 'Harvest: primary intent must be specification'),
(UUID(), 'harvest.intent_secondary_max', '1', 'integer', 'Harvest: max one additional intent')
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;
