-- SOURCE: CIE_Master_Developer_Build_Spec.docx Section 6 — gsc_baselines / CIS measurement
CREATE TABLE IF NOT EXISTS gsc_baselines (
    baseline_id                 CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    sku_id                      CHAR(36) NOT NULL,
    captured_at                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    triggered_by                CHAR(36),
    baseline_impressions        INT,
    baseline_clicks             INT,
    baseline_ctr                DECIMAL(6,4),
    baseline_avg_position       DECIMAL(8,2),
    baseline_organic_sessions   INT,
    baseline_conversion_rate    DECIMAL(8,6),
    baseline_revenue_organic    DECIMAL(12,2),
    baseline_bounce_rate        DECIMAL(6,4),
    d15_impressions             INT,
    d15_ctr                     DECIMAL(6,4),
    d15_avg_position            DECIMAL(8,2),
    d15_organic_sessions        INT,
    d15_conversion_rate         DECIMAL(8,6),
    d30_impressions             INT,
    d30_ctr                     DECIMAL(6,4),
    d30_avg_position            DECIMAL(8,2),
    d30_organic_sessions        INT,
    d30_conversion_rate         DECIMAL(8,6),
    d30_revenue_organic         DECIMAL(12,2),
    cis_score                   DECIMAL(6,2),
    measurement_status          ENUM('pending','d15_captured','d30_captured','complete') DEFAULT 'pending',
    FOREIGN KEY (sku_id) REFERENCES sku_master(sku_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
