#!/usr/bin/env python3
"""
Convert legacy MySQL SQL migrations into PostgreSQL-compatible SQL files.

DEPRECATED for greenfield deploy: converted files strip inline KEY/INDEX from CREATE TABLE.
Always apply spec-native indexes after conversion:

    python scripts/generate_pg_spec_indexes.py

Docker init runs database/postgres/init/03_spec_indexes.sql automatically.

This converter is intentionally conservative:
- It performs deterministic syntax rewrites for common MySQL constructs.
- It does not attempt semantic redesign of every migration.
- It writes converted output to database/postgres/migrations/.
"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "database" / "migrations"
DST_DIR = ROOT / "database" / "postgres" / "migrations"
BOOTSTRAP_FILE = ROOT / "database" / "postgres" / "init" / "01_migrations_bootstrap.sql"


def _convert(sql: str) -> str:
    out = sql

    # Remove MySQL session/charset noise.
    out = re.sub(r"(?im)^\s*SET\s+NAMES\s+utf8mb4\s*;?\s*$", "", out)
    out = re.sub(r"(?im)^\s*LOCK TABLES.*?;\s*$", "", out)
    out = re.sub(r"(?im)^\s*/\*!\d+.*?\*/\s*;?\s*$", "", out)
    out = re.sub(r"(?im)^\s*UNLOCK TABLES\s*;?\s*$", "", out)
    out = re.sub(r"(?im)^\s*DELIMITER\s+.*?\s*$", "", out)

    # Identifier quoting and UUID.
    out = out.replace("`", '"')
    out = re.sub(r"\buuid\(\)", "gen_random_uuid()", out, flags=re.IGNORECASE)
    out = out.replace("(gen_random_uuid())", "gen_random_uuid()::text")

    # Data type rewrites.
    out = re.sub(r"\bTINYINT\s*\(\s*1\s*\)", "BOOLEAN", out, flags=re.IGNORECASE)
    out = re.sub(r"\bINT\s+AUTO_INCREMENT\b", "INTEGER GENERATED BY DEFAULT AS IDENTITY", out, flags=re.IGNORECASE)
    out = re.sub(r"\bBIGINT\s+AUTO_INCREMENT\b", "BIGINT GENERATED BY DEFAULT AS IDENTITY", out, flags=re.IGNORECASE)
    out = re.sub(r"\bAUTO_INCREMENT\b", "", out, flags=re.IGNORECASE)

    # MySQL table options.
    out = re.sub(r"\)\s*ENGINE\s*=\s*InnoDB[^;]*;", ");", out, flags=re.IGNORECASE)
    out = re.sub(r"(?im)\s+CHARACTER\s+SET\s+\w+", "", out)
    out = re.sub(r"(?im)\s+COLLATE\s+\w+", "", out)
    out = re.sub(r"(?im)\s+ON\s+UPDATE\s+CURRENT_TIMESTAMP", "", out)

    # ENUM -> TEXT (preserves runtime compatibility without type explosion).
    out = re.sub(r"\bENUM\s*\(([^)]*)\)", "TEXT", out, flags=re.IGNORECASE)

    # MySQL date functions.
    out = re.sub(
        r"DATE_ADD\s*\(\s*NOW\(\)\s*,\s*INTERVAL\s+(\d+)\s+MINUTE\s*\)",
        r"NOW() + INTERVAL '\1 minutes'",
        out,
        flags=re.IGNORECASE,
    )

    # Remove inline KEY/INDEX definitions inside CREATE TABLE (MySQL syntax).
    out = re.sub(r"(?im)^\s*(UNIQUE\s+)?KEY\s+\"?[A-Za-z0-9_]+\"?\s*\([^)]+\)\s*,?\s*$", "", out)
    out = re.sub(r"(?im)^\s*INDEX\s+\"?[A-Za-z0-9_]+\"?\s*\([^)]+\)\s*,?\s*$", "", out)

    # Dynamic PREPARE/EXECUTE blocks are MySQL-specific; keep as comments for manual handling.
    out = re.sub(r"(?is)\bPREPARE\b.*?\bDEALLOCATE\s+PREPARE\b.*?;", "-- TODO(pg): removed MySQL PREPARE/EXECUTE block;", out)

    # Trigger blocks in MySQL syntax are not valid Postgres.
    out = re.sub(r"(?is)DROP\s+TRIGGER\s+IF\s+EXISTS\s+.*?;", "-- TODO(pg): review trigger drop", out)
    out = re.sub(r"(?is)CREATE\s+TRIGGER\b.*?END//", "-- TODO(pg): manual trigger conversion required", out)
    out = out.replace("END//", "")

    # SIGNAL syntax in triggers.
    out = re.sub(
        r"SIGNAL\s+SQLSTATE\s+'45000'\s+SET\s+MESSAGE_TEXT\s*=\s*'([^']*)'",
        r"RAISE EXCEPTION '\1'",
        out,
        flags=re.IGNORECASE,
    )

    # Remove trailing commas before table close.
    out = re.sub(r",\s*\)", "\n)", out)

    # Normalize excessive blank lines.
    out = re.sub(r"\n{3,}", "\n\n", out).strip() + "\n"
    return out


def main() -> int:
    DST_DIR.mkdir(parents=True, exist_ok=True)
    BOOTSTRAP_FILE.parent.mkdir(parents=True, exist_ok=True)

    migration_files = sorted(
        [p for p in SRC_DIR.glob("*.sql") if p.is_file()],
        key=lambda p: p.name,
    )

    bootstrap_chunks: list[str] = [
        "-- Auto-generated PostgreSQL bootstrap from legacy SQL migrations.",
        "-- Generated by scripts/convert_mysql_migrations_to_pg.py",
        "-- DEPRECATED alone for greenfield: run init/03_spec_indexes.sql (DECISION-014).",
        "-- After convert: python scripts/generate_pg_spec_indexes.py",
        "",
        "BEGIN;",
        "",
    ]

    for src in migration_files:
        dst = DST_DIR / src.name
        converted = _convert(src.read_text(encoding="utf-8", errors="ignore"))
        dst.write_text(converted, encoding="utf-8")
        bootstrap_chunks.append(f"-- {src.name}")
        bootstrap_chunks.append(f"\\i /docker-entrypoint-migrations/{src.name}")
        bootstrap_chunks.append("")

    bootstrap_chunks.append("COMMIT;")
    bootstrap_chunks.append("")
    BOOTSTRAP_FILE.write_text("\n".join(bootstrap_chunks), encoding="utf-8")

    print(f"Converted {len(migration_files)} files into {DST_DIR}")
    print(f"Bootstrap file: {BOOTSTRAP_FILE}")
    print(
        "WARNING: converter strips inline indexes. Run: python scripts/generate_pg_spec_indexes.py"
    )
    print("Greenfield Docker init applies database/postgres/init/03_spec_indexes.sql after migrations.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

