CREATE TABLE weekly_scores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_start DATE NOT NULL,
    score INT NOT NULL,
    notes TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_weekly_scores_score_range CHECK (score BETWEEN 1 AND 10)
);
