-- SOURCE: CIE_Master_Developer_Build_Spec.docx Section 5.3
INSERT INTO business_rules (rule_key, rule_value, data_type, module, label, description, approver_roles) VALUES
('tier.hero_percentile_threshold', '0.80', 'decimal', 'tier', 'Tier Hero Percentile Threshold', 'Top 20% of Commercial Priority Scores = Hero', 'admin'),
('tier.support_percentile_threshold', '0.30', 'decimal', 'tier', 'Tier Support Percentile Threshold', 'Above this & below Hero = Support', 'admin'),
('tier.harvest_percentile_threshold', '0.10', 'decimal', 'tier', 'Tier Harvest Percentile Threshold', 'Above this & below Support = Harvest; below = Kill', 'admin'),
('tier.margin_weight', '0.40', 'decimal', 'tier', 'Tier Margin Weight', 'Contribution Margin % weight in Priority Score', 'admin'),
('tier.cppc_weight', '0.25', 'decimal', 'tier', 'Tier Cppc Weight', 'CPPC weighting in Priority Score', 'admin'),
('tier.velocity_weight', '0.20', 'decimal', 'tier', 'Tier Velocity Weight', '90-day velocity weighting', 'admin'),
('tier.returns_weight', '0.15', 'decimal', 'tier', 'Tier Returns Weight', 'Return rate weighting', 'admin'),
('tier.manual_override_expiry_days', '90', 'integer', 'tier', 'Tier Manual Override Expiry Days', 'Days before manual tier override auto-expires', 'admin'),
('tier.auto_promotion_velocity_threshold', '0.30', 'decimal', 'tier', 'Tier Auto Promotion Velocity Threshold', 'Harvest-to-Support auto-promotion threshold (fractional velocity growth, e.g. 0.30 = 30%)', 'admin'),
('tier.kill_margin_floor', '5.0', 'decimal', 'tier', 'Tier Kill Margin Floor', 'SKUs with margin below this threshold are candidates for Kill tier assignment', 'admin'),
('tier.kill_no_sale_days', '90', 'integer', 'tier', 'Tier Kill No Sale Days', 'SKUs with no sales for this many days are candidates for Kill tier assignment', 'admin'),
('tier.kill_zero_velocity_threshold', '0', 'integer', 'tier', 'Tier Kill Zero Velocity Threshold', 'SKUs at or below this 90-day velocity are candidates for Kill tier assignment', 'admin'),
('chs.intent_alignment_weight', '0.25', 'decimal', 'chs', 'Chs Intent Alignment Weight', 'CHS weight: conversion / intent match signal', 'admin'),
('chs.semantic_coverage_weight', '0.20', 'decimal', 'chs', 'Chs Semantic Coverage Weight', 'CHS weight: topic cluster coverage', 'admin'),
('chs.technical_hygiene_weight', '0.20', 'decimal', 'chs', 'Chs Technical Hygiene Weight', 'CHS weight: G1â€“G7 gate pass rate', 'admin'),
('chs.competitive_gap_weight', '0.20', 'decimal', 'chs', 'Chs Competitive Gap Weight', 'CHS weight: GSC avg_position signal', 'admin'),
('chs.ai_readiness_weight', '0.15', 'decimal', 'chs', 'Chs Ai Readiness Weight', 'CHS weight: per-channel readiness score', 'admin'),
('chs.green_threshold', '70', 'integer', 'chs', 'Chs Green Threshold', 'CHS â‰¥ this = Green on dashboard', 'admin'),
('chs.amber_threshold', '40', 'integer', 'chs', 'Chs Amber Threshold', 'CHS â‰¥ this but below green = Amber; below = Red', 'admin'),
('cis.position_improvement_small_pts', '20', 'integer', 'cis', 'Cis Position Improvement Small Pts', 'CIS points for 1â€“4 spot position improvement', 'admin'),
('cis.position_improvement_large_pts', '40', 'integer', 'cis', 'Cis Position Improvement Large Pts', 'CIS points for 5+ spot improvement', 'admin'),
('cis.position_improvement_large_min', '5', 'integer', 'cis', 'Cis Position Improvement Large Min', 'Minimum spots to qualify for large band', 'admin'),
('cis.ctr_improvement_pts', '20', 'integer', 'cis', 'Cis Ctr Improvement Pts', 'CIS points if CTR improves at D+30', 'admin'),
('cis.impressions_improvement_pts', '15', 'integer', 'cis', 'Cis Impressions Improvement Pts', 'CIS points if impressions increase at D+30', 'admin'),
('cis.conversion_rate_improvement_pts', '25', 'integer', 'cis', 'Cis Conversion Rate Improvement Pts', 'CIS points if organic conversion rate improves', 'admin'),
('cis.success_threshold', '50', 'integer', 'cis', 'Cis Success Threshold', 'CIS â‰¥ this = Successful change', 'admin'),
('cis.measurement_window_d15', '15', 'integer', 'cis', 'Cis Measurement Window D15', 'Day-15 measurement trigger after publish', 'admin'),
('cis.measurement_window_d30', '30', 'integer', 'cis', 'Cis Measurement Window D30', 'Day-30 final CIS computation trigger', 'admin'),
('decay.yellow_flag_weeks', '1', 'integer', 'decay', 'Decay Yellow Flag Weeks', 'Consecutive zero-score weeks before yellow_flag status', 'admin'),
('decay.alert_weeks', '2', 'integer', 'decay', 'Decay Alert Weeks', 'Consecutive zeros before Content Writer alert', 'admin'),
('decay.zero_weeks_before_brief', '3', 'integer', 'decay', 'Decay Zero Weeks Before Brief', 'Consecutive zeros before AI auto-generates refresh brief (spec key)', 'admin'),
('decay.auto_brief_weeks', '3', 'integer', 'decay', 'Decay Auto Brief Weeks', 'Consecutive zeros before AI auto-generates refresh brief', 'admin'),
('decay.escalate_weeks', '4', 'integer', 'decay', 'Decay Escalate Weeks', 'Weeks after brief with no recovery before escalation', 'admin'),
('decay.auto_brief_deadline_days', '7', 'integer', 'decay', 'Decay Auto Brief Deadline Days', 'Days Content Writer has to complete a refresh brief', 'admin'),
('decay.hero_citation_target', '0.70', 'decimal', 'decay', 'Decay Hero Citation Target', 'Target AI citation rate for Hero SKUs (70% â‰¥ score 1)', 'admin'),
('decay.hero_citation_danger', '0.50', 'decimal', 'decay', 'Decay Hero Citation Danger', 'Citation rate below this triggers immediate escalation', 'admin'),
('decay.audit_question_count', '20', 'integer', 'decay', 'Decay Audit Question Count', 'Golden queries per category per weekly audit', 'admin'),
('decay.quorum_minimum', '3', 'integer', 'decay', 'Decay Quorum Minimum', 'Min AI engines that must respond for audit result to count', 'admin'),
('effort.hero_allocation_target', '0.60', 'decimal', 'effort', 'Effort Hero Allocation Target', 'Target % of content hours on Hero SKUs', 'admin'),
('effort.hero_allocation_danger', '0.55', 'decimal', 'effort', 'Effort Hero Allocation Danger', 'Below this auto-flags to KPI Conductor dashboard', 'admin'),
('effort.support_max_hours_per_quarter', '2', 'integer', 'effort', 'Effort Support Max Hours Per Quarter', 'Max effort per Support SKU per quarter', 'admin'),
('readiness.hero_primary_channel_min', '85', 'integer', 'readiness', 'Readiness Hero Primary Channel Min', 'Hero must reach this on primary channel within 30 days', 'admin'),
('readiness.hero_all_channels_min', '70', 'integer', 'readiness', 'Readiness Hero All Channels Min', 'Hero must reach this on all active channels', 'admin'),
('readiness.support_primary_channel_min', '60', 'integer', 'readiness', 'Readiness Support Primary Channel Min', 'Support minimum readiness on primary channel', 'admin'),
('readiness.gold_threshold', '90', 'integer', 'readiness', 'Readiness Gold Threshold', 'Readiness avg â‰¥ this = Gold maturity', 'admin'),
('readiness.silver_threshold', '65', 'integer', 'readiness', 'Readiness Silver Threshold', 'Readiness avg â‰¥ this = Silver maturity', 'admin'),
('readiness.deadline_days_after_completion', '30', 'integer', 'readiness', 'Readiness Deadline Days After Completion', 'Days after content completion before readiness minimum enforced', 'admin'),
('gates.answer_block_min_chars', '250', 'integer', 'gates', 'Gates Answer Block Min Chars', 'Minimum AI Answer Block character count (G4)', 'admin'),
('gates.answer_block_max_chars', '300', 'integer', 'gates', 'Gates Answer Block Max Chars', 'Maximum AI Answer Block character count (G4)', 'admin'),
('gates.best_for_min_entries', '2', 'integer', 'gates', 'Gates Best For Min Entries', 'Minimum Best-For entries for Hero/Support (G5)', 'admin'),
('gates.not_for_min_entries', '1', 'integer', 'gates', 'Gates Not For Min Entries', 'Minimum Not-For entries (G5)', 'admin'),
('gates.secondary_intent_max', '3', 'integer', 'gates', 'Gates Secondary Intent Max', 'Maximum secondary intents per SKU (G3)', 'admin'),
('gates.vector_similarity_min', '0.72', 'decimal', 'gates', 'Gates Vector Similarity Min', 'Minimum cosine similarity for vector validation to pass', 'admin'),
('gates.meta_title_max_chars', '65', 'integer', 'gates', 'Gates Meta Title Max Chars', 'Maximum meta title length', 'admin'),
('gates.meta_description_max_chars', '160', 'integer', 'gates', 'Gates Meta Description Max Chars', 'Maximum meta description length', 'admin'),
('gates.meta_description_min_chars', '120', 'integer', 'gates', 'Gates Meta Description Min Chars', 'Minimum meta description length', 'admin'),
('gates.description_word_count_min', '50', 'integer', 'gates', 'Gates Description Word Count Min', 'Minimum word count for product description (G6)', 'admin'),
('gates.description_min_chars', '100', 'integer', 'gates', 'Gates Description Min Chars', 'Minimum character count for description before vector check', 'admin'),
('sync.gsc_cron_schedule', '0 3 * * 0', 'string', 'sync', 'Sync Gsc Cron Schedule', 'GSC weekly pull â€” Sunday 03:00 UTC', 'admin'),
('sync.ga4_cron_schedule', '0 3 * * 1', 'string', 'sync', 'Sync Ga4 Cron Schedule', 'GA4 weekly pull â€” Monday 03:00 UTC', 'admin'),
('sync.erp_cron_schedule', '0 2 1 * *', 'string', 'sync', 'Sync Erp Cron Schedule', 'ERP monthly sync â€” 1st of month 02:00 UTC', 'admin'),
('sync.ai_audit_cron_schedule', '0 9 * * 1', 'string', 'sync', 'Sync Ai Audit Cron Schedule', 'AI audit run â€” Monday 09:00 UTC', 'admin'),
('sync.baseline_lookback_weeks', '2', 'integer', 'sync', 'Sync Baseline Lookback Weeks', 'Weeks to average for 14-day baseline calculations', 'admin'),
('gates.g1_blocked_title_prefixes', '', 'string', 'gates', 'G1 Blocked Title Prefix Terms (comma-separated)', 'Blocked title-start terms for intent-first title validation', 'admin'),
('gates.harvest_max_secondary_intents', '2', 'integer', 'gates', 'Harvest Tier Maximum Secondary Intents', 'Maximum secondary intents allowed for Harvest tier', 'admin')
ON DUPLICATE KEY UPDATE
  rule_value = VALUES(rule_value),
  data_type = VALUES(data_type),
  description = VALUES(description),
  module = VALUES(module),
  label = VALUES(label),
  approver_roles = VALUES(approver_roles),
  last_changed_at = CURRENT_TIMESTAMP;
