-- SOURCE: CIE_Master_Developer_Build_Spec.docx §4.5
-- FIX: AI-14 — AI Agent call logging table

CREATE TABLE IF NOT EXISTS ai_agent_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku_id VARCHAR(50) NOT NULL,
  function_called VARCHAR(100) NOT NULL,
  prompt_hash VARCHAR(64) NULL,
  response_received BOOLEAN DEFAULT FALSE,
  confidence_score DECIMAL(3,2) NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
