-- SOURCE: CIE_v2_3_Enforcement_Edition.pdf Section 7.1 — channel readiness scoring weights
-- SOURCE: CIE_Master_Developer_Build_Spec.docx Section 5.3 — business rules seed
INSERT IGNORE INTO business_rules (rule_key, rule_value, data_type, module, label, approver_roles)
VALUES
('channel.weight.cluster_id.google_sge', '10', 'integer', 'channel', 'Google SGE: Cluster ID weight', 'admin'),
('channel.weight.intent.google_sge', '15', 'integer', 'channel', 'Google SGE: Intent weight', 'admin'),
('channel.weight.answer_block.google_sge', '20', 'integer', 'channel', 'Google SGE: Answer Block weight', 'admin'),
('channel.weight.json_ld.google_sge', '20', 'integer', 'channel', 'Google SGE: JSON-LD weight', 'admin'),
('channel.weight.expert_authority.google_sge', '15', 'integer', 'channel', 'Google SGE: Expert Authority weight', 'admin'),
('channel.weight.best_not_for.google_sge', '10', 'integer', 'channel', 'Google SGE: Best/Not-For weight', 'admin'),
('channel.weight.wikidata.google_sge', '5', 'integer', 'channel', 'Google SGE: Wikidata weight', 'admin'),
('channel.weight.channel_specific.google_sge', '5', 'integer', 'channel', 'Google SGE: Channel-specific weight', 'admin'),
('channel.weight.cluster_id.amazon', '10', 'integer', 'channel', 'Amazon: Cluster ID weight', 'admin'),
('channel.weight.intent.amazon', '10', 'integer', 'channel', 'Amazon: Intent weight', 'admin'),
('channel.weight.answer_block.amazon', '5', 'integer', 'channel', 'Amazon: Answer Block weight', 'admin'),
('channel.weight.json_ld.amazon', '5', 'integer', 'channel', 'Amazon: JSON-LD weight', 'admin'),
('channel.weight.expert_authority.amazon', '10', 'integer', 'channel', 'Amazon: Expert Authority weight', 'admin'),
('channel.weight.best_not_for.amazon', '15', 'integer', 'channel', 'Amazon: Best/Not-For weight', 'admin'),
('channel.weight.wikidata.amazon', '0', 'integer', 'channel', 'Amazon: Wikidata weight', 'admin'),
('channel.weight.channel_specific.amazon', '45', 'integer', 'channel', 'Amazon: Channel-specific weight', 'admin'),
('channel.weight.cluster_id.ai_assistants', '10', 'integer', 'channel', 'AI Assistants: Cluster ID weight', 'admin'),
('channel.weight.intent.ai_assistants', '15', 'integer', 'channel', 'AI Assistants: Intent weight', 'admin'),
('channel.weight.answer_block.ai_assistants', '25', 'integer', 'channel', 'AI Assistants: Answer Block weight', 'admin'),
('channel.weight.json_ld.ai_assistants', '15', 'integer', 'channel', 'AI Assistants: JSON-LD weight', 'admin'),
('channel.weight.expert_authority.ai_assistants', '15', 'integer', 'channel', 'AI Assistants: Expert Authority weight', 'admin'),
('channel.weight.best_not_for.ai_assistants', '10', 'integer', 'channel', 'AI Assistants: Best/Not-For weight', 'admin'),
('channel.weight.wikidata.ai_assistants', '5', 'integer', 'channel', 'AI Assistants: Wikidata weight', 'admin'),
('channel.weight.channel_specific.ai_assistants', '5', 'integer', 'channel', 'AI Assistants: Channel-specific weight', 'admin'),
('channel.weight.cluster_id.own_website', '10', 'integer', 'channel', 'Own Website: Cluster ID weight', 'admin'),
('channel.weight.intent.own_website', '15', 'integer', 'channel', 'Own Website: Intent weight', 'admin'),
('channel.weight.answer_block.own_website', '15', 'integer', 'channel', 'Own Website: Answer Block weight', 'admin'),
('channel.weight.json_ld.own_website', '20', 'integer', 'channel', 'Own Website: JSON-LD weight', 'admin'),
('channel.weight.expert_authority.own_website', '10', 'integer', 'channel', 'Own Website: Expert Authority weight', 'admin'),
('channel.weight.best_not_for.own_website', '10', 'integer', 'channel', 'Own Website: Best/Not-For weight', 'admin'),
('channel.weight.wikidata.own_website', '5', 'integer', 'channel', 'Own Website: Wikidata weight', 'admin'),
('channel.weight.channel_specific.own_website', '15', 'integer', 'channel', 'Own Website: Channel-specific weight', 'admin'),
('channel.hero_primary_min_readiness', '85', 'integer', 'channel', 'Hero SKU minimum readiness on primary channel', 'admin'),
('channel.hero_active_min_readiness', '70', 'integer', 'channel', 'Hero SKU minimum readiness on all active channels', 'admin'),
('channels.delta_other', '0', 'integer', 'channel', 'Default channel delta for unknown channels', 'admin');
